### ISSUE TITLE
Is built in CODE server expected to work in official Nextcloud docker?

### ISSUE THREAD

**Issue by tanc** [CollaboraOnline/richdocumentscode#105]
I've been trying to get the CODE server set up in my network for two days with partial success. In the end I decided to install the built-in CODE server expecting it to work with the official Docker image (nextcloud:20) without modification. While it installs fine, when I open a document I see the menu bar and then it stalls with console reporting 400 errors on requests like:

```
https://nextcloud.[mydomain].net/apps/richdocumentscode/proxy.php?req=/lool/https%3A%2F%2Fnextcloud.[mydomain].net...
```

Obviously `[mydomain]` refers to my actual domain which I don't want to post publicly.

I should note that not all requests to `proxy.php` fail, this one returns 200 OK:

```
https://nextcloud.[mydomain].net/apps/richdocumentscode/proxy.php?req=/loleaflet/eec532f/loleaflet.html?WOPISrc=https%3A%2F%2Fnextcloud.[mydomain].net%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F623_ocar1woffn9k&title=TestDoc.xlsx&lang=en&closebutton=1&revisionhistory=1
```

So my request is really to know whether the built-in CODE server is expected to work without any modifications to the official Docker image? That is to say any of the official Docker images, based on Apache or otherwise.

If it is expected to work without modification I can start to debug the issue within my network, which uses the reverse proxy traefik.

**Comment by Steffen75** [comment]
I don't think that this a is a Docker specific problem. I'm also currently experiencing the same HTTP 400 errors like you do. When I try to open a document it's also just the menu bar on top and the rest of the screen remains empty.
But my Nextcloud installation is a classic one running directly on a dedicated server with a traditional Apache installation.

**Comment by itsthejb** [comment]
Now that the startup problems are fixed, having the problem that the app doesn't correctly handle being behind a reverse proxy: https://github.com/CollaboraOnline/richdocumentscode/issues/79#issuecomment-775176670

**Comment by Steffen75** [comment]
I don't think that's the problem in my case. There's no docker involved here. I've just upgraded the build-in CODE app package from Nextcloud's app store to 6.4.5. The HTTP 400 error has disappeared from my Firefox console. However the document still doesn't open correctly.

When choose "build-in CODE" in the settings of the Collabora Online App it says at least that the server is reachable.

Now when I choose "own server" and edit the URL there from https://mydomain/apps/richdocumentscode/proxy.php?req= into https://mydomain/custom_apps/richdocumentscode/proxy.php?req= like you mention in #79 and hit save the Collabora Online App says that no CODE server an be reached at all.

**Comment by itsthejb** [comment]
I think I've been able to fix this by using `ProxyPreserveHost On` in my Apache reverse proxy config...

**Comment by timar** [comment]
It works for me with the docker image called 'nextcloud'. I hope that's the official one. I use Apache reverse proxy. But it should not matter.
